version: "3"

services:
  postgres:
    build: ./db
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_house
    ports:
      - 54320:5432
    expose:
      - 5432
    volumes:
      - ./data:/data
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

  spark-master:
    build: ./spark
    environment:
      - SPARK_MODE=master
    ports:
      - 8085:8080
      - 8086:4040
    hostname: master
    expose:
      - 7077
    volumes:
      - ./my_spark.py:/opt/bitnami/spark/my_spark.py
    command: /opt/bitnami/spark/bin/spark-submit /opt/bitnami/spark/my_spark.py
    depends_on:
      - postgres

  spark-worker-1:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
    volumes:
      - ./my_spark.py:/opt/bitnami/spark/my_spark.py
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
    volumes:
      - ./my_spark.py:/opt/bitnami/spark/my_spark.py
    depends_on:
      - spark-master

volumes:
  postgres:
  pgadmin: